config/routes.rb
Rails.application.routes.draw do
get 'sessions/new'
root 'posts#index', as: 'home'

get 'about' => 'pages#about', as: 'about'
get 'signup' => 'users#new'
post 'signup' => 'users#create'
get 'login' => 'sessions#new'
post 'login' => 'sessions#create'
delete 'logout' => 'sessions#destroy'
get 'edit' => 'users#edit'
patch 'edit' => 'users#update'
resources :users, only: [:show, :edit, :update, :index, :destroy]
resources :posts do
  resources :comments
end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post
end

app/models/post.rb
class Post < ApplicationRecord
belongs_to :user
has_many :comments
  validates :title, presence: true, length: {minimum: 5}
end

app/models/user.rb
class User < ApplicationRecord
has_many :posts


 attr_accessor :remember_token
  has_secure_password


  def User.digest(string)
      cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
                                                    BCrypt::Engine.cost
      BCrypt::Password.create(string, cost: cost)
  end

  def User.new_token
    SecureRandom.urlsafe_base64
  end



  def remember
    self.remember_token = User.new_token
    update_attribute(:remember_digest, User.digest(remember_token))
  end

  def authenticated?(remember_token)
    return false if remember_digest.nil?
    BCrypt::Password.new(remember_digest).is_password?(remember_token)
  end

  def forget
    update_attribute(:remember_digest, nil)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include SessionsHelper
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
@post = Post.find(params[:post_id])
@comment = @post.comments.create(comment_params)
redirect_to post_path(@post)
  end

  private def comment_params
params.require(:comment).permit(:username, :body)

  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def about
    @heading ='Страничка про нас!'
    @text ='Немного текста'
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
   @post = Post.all
  end

def new
@post = Post.new
end

def show
  @post = Post.find(params[:id])
end

def edit
  @post = Post.find(params[:id])
end

def logged_in_user
      unless logged_in?
        flash[:danger] = "Please log in."
        store_location
        flash[:danger] = "Please log in."
        redirect_to login_url
      end
end

def update
@post = Post.find(params[:id])

   if(@post.update(post_params))
      redirect_to @post
   else
      render 'new'
   end
end

def destroy
  @post = Post.find(params[:id])

  @post.destroy
  redirect_to posts_path
end

def create
    @post = Post.new(post_params)
    @post.user = current_user


    if (@post.save)
      redirect_to @post
    else
      render 'new'
    end
end

private def post_params
  params.require(:post).permit(:title, :body)
end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def destroy
  end

  def create
    user = User.find_by(email: params[:session][:email])
    if user && user.authenticate(params[:session][:password])
      log_in user
      params[:session][:remember_me] == '1' ? remember(user) : forget(user)
      redirect_back_or user
#  end
    else
    flash.now[:danger] = 'Invalid email/password combination'
    render 'new'
    end
  end

    def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  def logged_in?
    !current_user.nil?
  end

  def destroy
    log_out if logged_in?
    redirect_to home_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
before_action :logged_in_user, only: [:index, :edit, :update, :destroy]
before_action :correct_user,   only: [:edit, :update]
before_action :admin_user,     only: :destroy

  def destroy
    User.find(params[:id]).destroy
    flash[:success] = "User deleted"
    redirect_to users_url
  end

  def admin_user
        redirect_to(posts_path) unless current_user.admin?
  end

  def index
    @users = User.all
  end

  def new
    @user = User.new
  end

  def show
    @user = User.find(params[:id])
  end

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to user_path(@user)
    else
      render 'new'
    end
  end

  def edit
      @user = User.find(params[:id])
  end

  def update
  @user = User.find(params[:id])

     if @user.update_attributes(user_params)
        redirect_to @user
     else
        render 'edit'
     end
  end

  def logged_in_user
      unless logged_in?
        store_location
        flash[:danger] = "Please log in."
        redirect_to login_url
      end
    end

    def correct_user
      @user = User.find(params[:id])
      redirect_to(posts_path) unless current_user?(@user)

    end

  private
  def user_params
    params.require(:user).permit(:name, :email, :password)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def log_in(user)
    session[:user_id] = user.id
  end

  def remember(user)
      user.remember
      cookies.permanent.signed[:user_id] = user.id
      cookies.permanent[:remember_token] = user.remember_token
    end

    def current_user
      if (user_id = session[:user_id])
        @current_user ||= User.find_by(id: user_id)
      elsif (user_id = cookies.signed[:user_id])
        user = User.find_by(id: user_id)
        if user && user.authenticated?(cookies[:remember_token])
          log_in user
          @current_user = user
        end
      end
    end

    def current_user?(user)
        user == current_user
    end

  def logged_in?
      !current_user.nil?
  end

  def redirect_back_or(default)
      redirect_to(session[:forwarding_url] || default)
      session.delete(:forwarding_url)
  end

  def store_location
      session[:forwarding_url] = request.url if request.get?
  end

  def log_out
    forget(current_user)
    session.delete(:user_id)
    @current_user = nil
  end

  def forget(user)
    user.forget
    cookies.delete(:user_id)
    cookies.delete(:remember_token)
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_footer.html.erb
<footer class="footer">
     <div class="container">
       <div class="row">
         <span class="text-muted col-9">Все права защищены © 2018!</span>
           <span class="text-muted col-3">Соц. кнопки:</span>
       </div>
     </div>
    </footer>

app/views/layouts/_header.html.erb
<nav class=" navbar navbar-expand-md navbar-dark bg-dark ">


  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExampleDefault" aria-controls="navbarsExampleDefault" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarsExampleDefault">
    <ul class="navbar-nav mr-auto">
        <span class="p-2 text-dark"><%= link_to "Home Page", home_path, :class => 'text-warning' %></span>
        <span class="p-2 text-dark"><%= link_to "Добавление статьи", new_post_path, :class => 'text-warning' %></span>
        <span class="p-2 text-dark"><%= link_to "О нас", about_path, :class => 'text-warning' %></span>


    </ul>
    <form class="form-inline my-2 my-lg-0">



      <% if logged_in? %>



        <!-- Временно, заброшу в "dropdown-menu" -->

        <span class="pl-2"><%= link_to "Profile", current_user, :class => 'text-warning' %></span>
        <span class="pl-2"><%= link_to "| Log out", logout_path, method: "delete", :class => 'text-warning' %></span>
        <span class="pl-2"><%= link_to "Edit", edit_user_path(current_user), :class => 'text-warning' %></span>
        <span class="pl-2"><%= link_to "Users", users_path, :class => 'text-warning' %></span>
        <!--  -->

      <% else %>

          <span  id="signUp" class="text-dark btn btn-outline-light">
            <%= link_to "Войти", login_path %>
          </span>

      <% end %>

    </form>

  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Simpleblog</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css' %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="bg-secondary">
    <%= render 'layouts/header' %>

    <div class="container ">
        <br>
        <% flash.each do |message_type, message| %>
          <div class="alert alert-<%= message_type %>"><%= message %></div>
        <% end %>
        <%= yield %>
        <br>
        <hr>
    </div>
    <%= render 'layouts/footer' %>
    <br>    <br>    <br>
    <div id= "debug" class="container bg-white rounded"><%= debug(params) if Rails.env.development? %></div>
  </body>
</html>

app/views/pages/about.html.erb
<h4 class="text-warning"><%= @heading %></h4>
<h4 class="text-white"><%= @text %></h4>

app/views/posts/edit.html.erb
<h2 class="text-warning">Редактирование поста</h2>
<%= form_for :post, url: post_path(@post), method:  :patch do |f| %>
<% if @post.errors.any? %>
<% @post.errors.full_messages.each do |msg| %>
<div class="alert alert-danger"><%= msg %></div>
<% end %>
<% end %>
  <h5 class="text-white">
Название<br>
<%= f.text_field(:title, {:class => 'form-control bg-dark text-white'}) %>

  </h5><br>
  <h5 class="text-white">
Текст статьи<br>
<%= f.text_area(:body, {:class => 'form-control bg-dark text-white'}) %>

  </h5>

<p>
  <%= f.submit({:class => 'btn btn-warning'}) %>
  </p>
  <% end %>

app/views/posts/index.html.erb
<h1 class="text-warning">Главная страница</h1>
<% @post.each do |post| %>
<div class="alert bg-dark">
<h4 class="text-white"><%= post.user.name %></h4>
<br>
<h3 class="text-white"><%= post.title %></h3>
<h5 class="text-white"><%= post.body %></h5>

<%= link_to "Читать далее", post_path(post), :class => 'btn btn-warning' %>
</div>
<% end %>

app/views/posts/new.html.erb
<h1 class="text-warning">Добавление нового поста</h1>
<%= form_for :post, url: posts_path do |f| %>
<% if @post.errors.any? %>
<% @post.errors.full_messages.each do |msg| %>
<div class="alert alert-danger"><%= msg %></div>
<% end %>
<% end %>
  <h5 class="text-white">
Название<br>
<%= f.text_field(:title, {:class => 'form-control bg-dark text-white'}) %>

  </h5><br>
  <h5 class="text-white">
Текст статьи<br>
<%= f.text_area(:body, {:class => 'form-control bg-dark text-white'}) %>

  </h5>

<p>
  <%= f.submit({:class => 'btn btn-warning'}) %>
  </p>
  <% end %>

app/views/posts/show.html.erb
<h3 class="text-warning"><%= @post.title %></h3>
<h5 class="text-white"><%= @post.body %></h5>
<hr>
<div class="container float-right">
  <div class="float-right text-white">
    <%= @post.user.name %>
    </div>

<%= link_to "Редактировать", edit_post_path(@post), :class => 'btn btn-warning' %>
<%= link_to "Удалить пост", post_path(@post), method: :delete, data:{confirm: "Хотите удалить статью?"}, :class => 'btn btn-warning text-danger' %>
<hr>
</div>
<h3 class="text-white">Все комментарии</h3>
<% @post.comments.each do |comment| %>
<div class="alert alert-light">
<p><strong><%= comment.username %></strong>: <%= comment.body %></p>
</div>
<% end %>

<hr>
<h5 class="text-white">Комментарии</h5>
<%= form_for([@post, @post.comments.build]) do |f| %>
  <p class="text-white">
Пользователь<br>
<%= f.text_field(:username, {:class => 'form-control bg-dark text-white'}) %>

</p>
  <p class="text-white">
Комментарий<br>
<%= f.text_area(:body, {:class => 'form-control bg-dark text-white'}) %>

  </p>

<p>
  <%= f.submit("Добавить комментарий", {:class => 'btn btn-warning'}) %>
  </p>
  <% end %>

app/views/users/_user.html.erb
<li class="text-dark">
  <%= link_to user.name, user, :class => 'text-white' %>
  <% if current_user.admin? && !current_user?(user) %> ||
     <%= link_to "delete", user, method: :delete,
                                  data: { confirm: "You sure?" }, :class => 'text-white' %>
  <% end %>
</li>

app/views/users/edit.html.erb
<h1 class="text-warning">Редактирование профиля</h1>
<%= form_for :user, url: user_path(@user), method:  :patch do |f| %>
<% if @user.errors.any? %>
<% @user.errors.full_messages.each do |msg| %>
<div class="alert alert-danger"><%= msg %></div>
<% end %>
<% end %>
<br><br>
  <h6 class="text-white">
Name<br>
<%= f.text_field(:name, {:class => 'form-control bg-dark text-white'}) %>

  </h6><br>
  <h6 class="text-white">
 email<br>
<%= f.text_field(:email, {:class => 'form-control bg-dark text-white'}) %>

  </h6><br>

  <h6 class="text-white">
 password<br>
<%= f.password_field(:password, {:class => 'form-control bg-dark text-white'}) %>

  </h6><br>

  <h6 class="text-white">
 password confirm<br>
<%= f.password_field(:password_confirmation, {:class => 'form-control bg-dark text-white'}) %>

  </h6><br>


<p>
  <%= f.submit({:class => 'btn btn-warning'}) %>
  </p>
  <% end %>

app/views/users/index.html.erb
<h1 class="text-warning">All users</h1>

<ul class="users">
  <%= render @users %>
</ul>

app/views/users/new.html.erb
<h1 class="text-warning">Sign up</h1>
<%= form_for :user, url: signup_path do |f| %>


  <h5 class="text-white">
Name<br>
<%= f.text_field(:name, {:class => 'form-control bg-dark text-white'}) %>

  </h5>
  <h5 class="text-white">
email<br>
<%= f.text_area(:email, {:class => 'form-control bg-dark text-white'}) %>

  </h5>
  <h5 class="text-white">>
password<br>
<%= f.text_field(:password, {:class => 'form-control bg-dark text-white'}) %>

  </h5>

<h5 class="text-white">
  <%= f.submit({:class => 'btn btn-warning'}) %>
  </h5>
  <% end %>

app/views/users/show.html.erb
<div class="alert bg-dark">
<h5 class="text-warning"><%= @user.name %> </h5>
<h6 class="text-warning"><%= @user.email %></h6>
</div>